# Generated by Django 4.2.5 on 2023-10-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_nueva_propuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nueva_propuesta',
            name='nombre_asesor_contact_center',
        ),
    ]
