# Generated by Django 4.2.5 on 2023-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_nueva_propuesta_vigencia_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nueva_propuesta',
            name='vigencia_certificado',
            field=models.CharField(choices=[(3, 'Un año'), (4, 'Dos años')], default=1, max_length=2),
        ),
    ]
