# Generated by Django 4.2.5 on 2023-10-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_nueva_propuesta_vigencia_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nueva_propuesta',
            name='vigencia_certificado',
            field=models.CharField(max_length=100),
        ),
    ]
