# Generated by Django 4.2.5 on 2023-10-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_remove_nueva_propuesta_vigencia_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nueva_propuesta',
            name='tipo_certificado',
            field=models.CharField(choices=[(10, 'Facturación Electrónica - Persona Jurídica'), (11, 'Facturación Electrónica - Persona Natural'), (6, 'Comunidad Académica'), (9, 'Pertenencia Empresa'), (7, 'Profesional Titulado'), (8, 'Representante Legal'), (12, ' Función Púbica'), (13, 'Persona Jurídica'), (14, 'Función Publica para SIIF Nación'), (5, 'Persona Natural'), (15, 'Persona Natural Para Actividad Comercial (Rut)')]),
        ),
    ]
