# Generated by Django 4.2.5 on 2023-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_nueva_propuesta_tipo_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nueva_propuesta',
            name='tipo_certificado',
            field=models.CharField(max_length=100),
        ),
    ]
