# Generated by Django 4.2.5 on 2023-10-26 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_alter_nueva_propuesta_tipo_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nueva_propuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nueva_propuesta',
            name='precio_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nueva_propuesta',
            name='precio_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
