# Generated by Django 4.2.5 on 2023-10-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_nueva_propuesta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nueva_propuesta',
            name='asesor',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
